# Generated by Django 3.2.12 on 2022-03-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='nationality',
            old_name='name',
            new_name='nation',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
    ]
